const WINNER_X = "STATUS_WINNER_X"
const WINNER_O = "STATUS_WINNER_O"
const NOT_WINNER_YET = "STATUS_NOT_WINNER_YET"
const GAME_NOT_INIT = "STATUS_GAME_NOT_INIT"

export {
    GAME_NOT_INIT,
    WINNER_O,
    WINNER_X,
    NOT_WINNER_YET
} 